
name: menuconfig_lts
on:
  workflow_dispatch:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  schedule:
    #- cron: '5 1 * * 6'
    #- cron: '5 1 * * 2,4'
    #- cron: '5 1 * * 2'
    - cron: '5 1 * * 4'

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  menuconfig_lts:
    runs-on: ubuntu-latest
    #runs-on: ubuntu-20.04
    #runs-on: buildjet-2vcpu-ubuntu-2004
    #runs-on: buildjet-64vcpu-ubuntu-2004
    steps:
    - name: users
      shell: bash
      run: |
        sudo -u ubuntu -n bash -c 'sudo -n useradd runner --non-unique -u $UID -g $UID' || true
        sudo -u ubuntu -n bash -c 'sudo -n groupadd runner --non-unique -g $UID' || true
        sudo -u runner -n bash -c 'sudo -n echo $USER $UID' || true
        true
      # Apparently may increase buildJet 'runner' to 77GB (instead of 61GB).
      # Apparently may increase Github Actions 'runner' to 59GB (instead of 31GB) .
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        #root-reserve-mb: 512
        root-reserve-mb: 2048
        #temp-reserve-mb: 100
        temp-reserve-mb: 300
        #swap-size-mb: 128
        swap-size-mb: 192
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
    - uses: actions/checkout@v2
    - name: _getMinimal_cloud
      shell: bash
      run: |
        ./ubiquitous_bash.sh _getMinimal_cloud
      timeout-minutes: 90
    - name: _fetchKernel_lts
      shell: bash
      run: |
        ./ubiquitous_bash.sh _fetchKernel_lts
      timeout-minutes: 180
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      # ssh -i <path-to-key> <tmate-connection-string>
      with:
          limit-access-to-actor: true
      timeout-minutes: 320
    - name: artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-lts
        path: |
          ./
      timeout-minutes: 45





